"""audit

Revision ID: 1c202db3e3e2
Revises: 05d233b19ee9
Create Date: 2026-06-05 09:37:50.760754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c202db3e3e2'
down_revision: Union[str, Sequence[str], None] = '05d233b19ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('correlation_key', sa.String(length=128), nullable=False),
    sa.Column('target_service', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_correlation_key'), ['correlation_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entries_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_correlation_key'))

    op.drop_table('audit_entries')
    # ### end Alembic commands ###
